title: Hanlin Chen

theme: jekyll-theme-minimal

logo: chl.jpg

classes: wide

description: > # your text below (remove <br> elements if you don't need line breaks)
  A home page to expand on my data science projects. All source code can be found on my GitHub profile!
  <br><br>  
  <a href="cv.pdf">View Resume </a>   
  <br>
