title: Hanlin Chen (陈翰林)

theme: jekyll-theme-minimal
remote_theme: ankitsultana/researcher@gem

nav:
- name: "About"
  link: "/hlchen/"
- name: "Curriculum Vitae"
  link: "cv.pdf"
- name: "GitHub"
  link: https://github.com/HLinChen
